### ISSUE TITLE
gen2.py issue: "ValueError: not enough values to unpack (expected 2, got 1)"

### ISSUE THREAD

**Issue by SuperBruceJia** [m3hrdadfi/dash-tf-docset#1]
Hi,

Thanks a lot for your great work. It helps a lot.

When I tried to follow the instructions to generate DocSet, it seemed that it cannot be executed under Python 3.8.
The execution error is attached to this message, please check it.
Could u help me with this issue? 

Thanks in advance.

Best,

Shuyue

`Error Message`:

```shell
~/Desktop/dash-tf-docset(master*) » python gen2.py -d ./output -v v2.0.0                                                                           2 ↵

########################################################################
#                      Installing tensorflow-docs                      #
########################################################################

run_task: pip freeze
170B [00:00, 293B/s]  
Traceback (most recent call last):
  File "gen2.py", line 26, in <module>
    main(args.dir_path, args.version)
  File "gen2.py", line 7, in main
    tf_auto_doc_setup.run()
  File "/Users/shuyuej/Desktop/dash-tf-docset/src/tf_auto_doc_setup.py", line 189, in run
    status = self._install_tf_doc()
  File "/Users/shuyuej/Desktop/dash-tf-docset/src/tf_auto_doc_setup.py", line 127, in _install_tf_doc
    if not search_package('tensorflow_docs', None):
  File "/Users/shuyuej/Desktop/dash-tf-docset/src/utils.py", line 76, in search_package
    packages = pip_get_all_packages()
  File "/Users/shuyuej/Desktop/dash-tf-docset/src/utils.py", line 71, in pip_get_all_packages
    pkgs = [(pkg.lower().replace('-', '_'), version) for pkg, version in pkgs]
  File "/Users/shuyuej/Desktop/dash-tf-docset/src/utils.py", line 71, in <listcomp>
    pkgs = [(pkg.lower().replace('-', '_'), version) for pkg, version in pkgs]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by SuperBruceJia** [comment]
I used [this repo](https://github.com/reuben/gen_tf_docset). And it could work well.
